/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://jyt2g52r5bhpremloryqc427zq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-s4ufgphacrd2fin5xzlki4uzdi",
    "aws_cognito_identity_pool_id": "us-east-1:f78d9f27-af8f-479b-b740-08c89435c1e5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_FVD3YUnaj",
    "aws_user_pools_web_client_id": "55p4l7ikn8sh5gvb69ml5v9g8b",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "restaurants-myamplify",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
